.circleci/config.yml
pages/desktop/details.py
test_home.py
test_install.py
test_login.py
test_search.py

A new attempt at setting up CircleCi. Hope this works now. 
**Edit:** The build was successful. For the moment, I've only used one test in the run command to make sure that the environment works. I will add more tests after review. 
**Update**: 
- renamed `build` job as `test` in config.yml
- updated the install tests and added some extra wait to avoid intermittent test failures
- added more tests to run on CI: tests currently running are search, home and install

Improvements to the circleci config file

---

test_install.py

Changed the test data for the theme installation test. The previous theme can no longer be installed on stage. 
I'm going to merge this pull request without requesting a review because it contains only some test data changes.

Fix install test

---

conftest.py
pages/desktop/base.py
pages/desktop/details.py
pages/desktop/extensions.py
pages/desktop/home.py
pages/desktop/search.py
pages/desktop/themes.py
regions/desktop/categories.py
regions/desktop/search.py
regions/desktop/shelves.py
test_extensions.py
test_home.py
test_install.py
test_search.py
test_themes.py

Remove mobile view resolution and the mark_desktop_only skip reason in tests

---

.circleci/config.yml

Adding a scheduled workflow for stage release

---

pages/desktop/details.py
stage.json
tests/test_addon_detail.py

Add test for Contribute card in addon detail

---

tests/test_home.py

Another update to the AMO footer links

Update AMO policies footer link

---

tests/test_addon_detail.py
tests/test_install.py
tests/test_search.py

Switch to 'f' strings

---

pages/desktop/home.py
tests/test_home.py

Updated the locator for the Recommended extensions homepage shelf and changed to Social footer link from 'facebook' to 'instagram'
I'm merging this PR without a review because the changes are very low risk (only test data).

Test updates

---

pages/desktop/details.py
stage.json
tests/test_addon_detail.py

A few tests that cover the add-on detail meta (main) card.

Tests covering the add-on meta card

---

pages/desktop/details.py
stage.json
tests/test_addon_detail.py

I'm adding one more test to cover non-recommended add-ons, which have a couple of particularities.

Test for non-promoted addons meta card

---

pages/desktop/details.py

A very small update to the Learn more about permissions link locator.

Small update to add-on Permissions test

---

pages/desktop/details.py
tests/test_addon_detail.py

Tests covering this section of the card:

First set of tests for the addon More Info card

---

pages/desktop/details.py
pages/desktop/versions.py
tests/test_addon_detail.py

Second set of tests for the More info card

---

.pre-commit-config.yaml
pages/desktop/base.py
pages/desktop/categories.py
pages/desktop/category.py
pages/desktop/collections.py
pages/desktop/details.py
pages/desktop/edit_addon.py
pages/desktop/edit_theme.py
pages/desktop/extensions.py
pages/desktop/home.py
pages/desktop/reviews.py
pages/desktop/search.py
pages/desktop/themes.py
pages/desktop/users.py
regions/desktop/categories.py
regions/desktop/search.py
regions/desktop/shelves.py
requirements.dev.txt
scripts/generate_fxa_email.py
tests/conftest.py
tests/test_addon_detail.py
tests/test_extensions.py
tests/test_home.py
tests/test_install.py
tests/test_search.py
tests/test_themes.py
tests/test_users.py

- Lint with black 
- Add black in pre-commit for consistency #211 
- Switch to single quote strings #145

Setup pre-commit for linting

---

pages/desktop/details.py
tests/test_addon_detail.py

A few tests that checking the screenshot viewer from the add-on detail page.

Tests covering the addon screenshots component

---

pages/desktop/details.py
tests/test_addon_detail.py

More add-on detail stuff (a few more tests and I'll be done with it, for now at least)

More tests for the add-on detail page

---

pages/desktop/details.py
tests/test_addon_detail.py
tests/test_home.py

There have been a few small ux changes that caused some test failures.

A few test fixes

---

pages/desktop/details.py
stage.json
tests/test_addon_detail.py

Final set of tests for the add-on detail page. I will add more in the future if there's need for more coverage, but now I need to start focusing on other sections.

Final detail tests

---

pages/desktop/home.py
tests/test_home.py

Update locator for the homepage shelves browse all link

---

pages/desktop/details.py
pages/desktop/reviews.py
stage.json
tests/test_ratings.py

A set of tests that are checking the "All reviews" page functionality - like filtering by score, flagging reviews, the list of user reviews.

Tests covering the All reviews page components

---

pages/desktop/details.py
pages/desktop/search.py
requirements.txt
tests/test_addon_detail.py

Categories related to the add-on detail have been added in the More info card. I've added a test to cover this functionality.

Add a test for the new addon categories in addon More info card

---

pages/desktop/reviews.py
stage.json
tests/test_ratings.py

This is the last set of tests (for now) covering the ratings and reviews feature.

Add remaining tests for ratings and reviews

---

pages/desktop/base.py
pages/desktop/home.py
stage.json
tests/test_home.py

A few more tests for the homepage, covering the developer hub and extension workshop links in the header, the Primary hero banner and the Secondary hero modules.

Add more homepage tests

---

pages/desktop/home.py
scripts/custom_waits.py
scripts/reusables.py
tests/test_home.py
tests/test_search.py

These tests are verifying the homepage shelves items in more detail .

Tests for the homepage shelves

---

pages/desktop/details.py
tests/test_addon_detail.py

Add-on tags have been added in the More info section. I'm adding a test to cover this new content.

A test for the tags section in detail pages

---

pages/desktop/base.py
tests/test_users.py

These tests are checking the links present in the user dropdown menu form the AMO header.

Add tests for the user menu navigation in AMO header

---

pages/desktop/base.py
pages/desktop/details.py
pages/desktop/login.py
pages/desktop/reviews.py
pages/desktop/search.py
tests/test_addon_detail.py

Since we switched to parallelism = 4, there were a few repeating intermittent test failures. I've tried to make some tweaks to hopefully improve stability for those tests.

A few tweaks to (hopefully) improve test stability

---

tests/test_home.py

Just a small update to browser footer links.

Update links for browser footer links

---

pages/desktop/base.py
pages/desktop/login.py
pages/desktop/reviews.py
pages/desktop/search.py
tests/test_users.py

I've started adding wait messages in the following pages:
- `pages/desktop/base.py`
- `pages/desktop/login.py`
- `pages/desktop/reviews.py`
- `pages/desktop/search.py`
I didn't want to have a huge patch, so the other pages will be handled in other patches.
I've also tweaked the waits in two functions:  `pages/desktop/base.py - logged_in` and `pages/desktop/reviews.py - click_reply_to_review`

Part one: add wait messages in some of our pages

---

pages/desktop/users.py
stage.json
tests/test_users.py

Tests for the notifications section in the Edit profile page.

Add tests for user notifications

---

pages/desktop/search.py
pages/desktop/users.py
tests/test_users.py

Add tests for the user profile extensions and themes cards

---

pages/desktop/reviews.py
tests/test_home.py
tests/test_ratings.py
tests/test_users.py

- added `wait_for_page_to_load()` to some older homepage tests
- a small change to the login test to avoid stale element exceptions when trying to read the user `display_name` after login is successful
- edit the method for opening the flag review menu

A few more stability tweaks

---

pages/desktop/details.py
pages/desktop/users.py
stage.json
tests/conftest.py
tests/test_users.py

The user view profile page allows users to write, edit and delete reviews.
Other users can also report an abuse report when accessing another user's view profile page.

Add tests for reviews and abuse report in user profile

---

pages/desktop/login.py

This PR won't be merged in its current state. It is mostly used for debugging login issues occurring on CI since locally I could not reproduce them to figure out where the issue is. 
Update: the PR is ready for a review now.

Add more steps in the login function to debug login failure on CI

---

pages/desktop/details.py
stage.json
tests/test_collections.py

Final set of tests for collections.

Last set of tests for collections

---

pages/desktop/base.py
tests/test_home.py

- a new link to the addons blog has been added in the header - next to the developer hub and extension workshop links => a test was added to cover this addition
- the link to the addons blog from the More menu has been removed => removed test coverage for that
- the product footer links have been updated => test was updated as well

Update some homepage tests

---

pages/desktop/devhub.py
tests/test_devhub.py

Tests covering the Developr Hub homepage header menu options.

Tests for the devhub header menu

---

pages/desktop/devhub.py
stage.json
tests/test_devhub.py

Added tests for:
- sign out from devhub
- page content sections - log out view - there are 3 main sections in total:
- overview
- ready to submit
- get involved with the community

Tests for devhub homepage logout view

---

pages/desktop/devhub.py
stage.json
tests/test_devhub.py

Test for this section in the devhub footer:

Tests for devhub Connect footer

---

.gitignore
pages/desktop/developers/devhub_home.py
pages/desktop/developers/edit_addon.py
pages/desktop/developers/submit_addon.py
tests/test_devhub_home.py

Resubmit PR #431

---

pages/desktop/developers/devhub_home.py
stage.json
tests/test_devhub_home.py

Tests covering the Resources footer from the Developer Hub homepage:

Add tests for the resources footer available for logged in users

---

pages/desktop/frontend/blog_homepage.py
prod.json
tests/frontend/test_blog_homepage.py

1. created prod.json where I put base_url for production site so tests can be ran on both prod and stage
2. created page objects for blog homepage
3. created tests for blog homepage

Addons homepage blog

---

pages/desktop/frontend/details.py
pages/desktop/frontend/reviews.py
prod.json
stage.json
tests/devhub/test_devhub_home.py
tests/frontend/test_addon_detail.py
tests/frontend/test_blog.py
tests/frontend/test_collections.py
tests/frontend/test_extensions.py
tests/frontend/test_home.py
tests/frontend/test_ratings.py
tests/frontend/test_search.py
tests/frontend/test_themes.py
tests/frontend/test_users.py

Changes in this PR:
- added more required variables in `prod.json`
- small tweaks to some methods and tests to make them compatible with prod data
- mark tests to be collected by the sanity run with `@pytest.mark.sanity`

Select tests for sanity run and update some variables

---

pages/desktop/frontend/details.py
tests/frontend/test_addon_detail.py

- added test_developer_comments() to check if section header and content are displayed
- modified test_addon_ratings_card() to also verify if report button and see all reviews link are displayed

Addon detail coverage

---

pages/desktop/base.py
pages/desktop/frontend/users.py
stage.json
tests/frontend/test_users.py

- add extra validations in some tests
- made test_user_update_url() to test URL validations
- made test_user_update_profile() to test if existing profile info can be updated
- modify upload_picture() from users.py to work on macOS too

improve coverage on test_users.py

---

pages/desktop/frontend/details.py
pages/desktop/frontend/reviews.py
stage.json
tests/frontend/test_ratings.py

-created tests for throttled request error
-created tests for rating/review term usage
-created test for featured review
-made test_write_review_in_all_reviews_page() to also test the cancel button when writing a review

Coverage test rating

---

pages/desktop/frontend/collections.py
tests/frontend/test_collections.py

- added test for delete collection confirmation message
- small modifications in some tests to improve coverage
- added methods in framework for some tests
- remove skip mark from test_collection_addon_notes()

add test for confirm delete dialog and modify other tests

---

tests/frontend/test_blog.py

Add check for add-on summary in addon names from the blog don't match those in about:addons.

Add alternative check for addon blog installs

---

.circleci/config.yml

Add Python 3.10 as version used in CircleCI.

Fix python version issue

---

.circleci/config.yml

Run python scripts with `py -3.9`

Use python from windows orb

---

pages/desktop/about_addons.py
tests/frontend/test_sanity.py

Added an alternate check for addon installs in about addons (check for author name is names don't match)

update to about addon extension installs

---

tests/frontend/test_users.py

Exclude the `test_user_data_for_deleted_profile` from sanity.

Exclude test from sanity

---

pages/desktop/frontend/versions.py
regions/desktop/rating_stats_card.py

Added page objects for: -add-on version page
-add-on reviews card

add page objects for versions page and review card

---

pages/desktop/frontend/versions.py
stage.json
tests/frontend/test_versions.py

I added tests for add-on versions page. I temporary omitted to test the 'download file' link from older versions.

Addon versions tests

---

regions/desktop/rating_stats_card.py
tests/frontend/test_ratings.py

Added tests for add-on rating cards.

Tests rating card

---

pages/desktop/developers/devhub_home.py
pages/desktop/developers/edit_addon.py
pages/desktop/developers/manage_versions.py
pages/desktop/developers/submit_addon.py
stage.json
tests/devhub/test_addon_submissions.py

- add page objects for listed add-on submission form
- add tests for listed add-on submission, checking if auto-approval works and if the last update date is correct

Add more submission tests

---

pages/desktop/developers/devhub_home.py
pages/desktop/developers/edit_addon.py
prod.json
tests/frontend/test_search.py
tests/frontend/test_users.py

- fixed the last updated methods from devhub to return a uniform date structure
- reordered some user tests
- switched to session auth for the `reusable_user` tests

Sanity small updates

---

.circleci/config.yml
pages/desktop/base.py
pages/desktop/frontend/home.py
regions/desktop/categories.py
tests/frontend/test_translations.py
translations.json

I created tests for home page, extensions page and themes page.
I tested the translations for italiano, espanol, deutsch and francais.

add tests for page translations

---

pages/desktop/frontend/login.py

Update wait condition in fxa login method to be compatible with both dev and stage.

Update a wait condition in the fxa login method

---

api/api_helpers.py
pages/desktop/frontend/login.py
requirements.txt
tests/frontend/test_sanity.py
tests/frontend/test_users.py

A new  set of API tests, including:
- uploading listed extension
- editing extension details
- deleting extension

Second set of tests for the addon submission API

---

tests/api/test_addon_uploads.py

This PR includes tests that are using the [PUT endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#put-create-or-edit) to upload addons. They cover both valid and invalid scenarios.

Add tests for the PUT submission method

---

api/payloads.py
tests/api/test_addon_uploads.py

- tests for editing an addon with the wrong user
- tests for editing version details
- tests for editing an addon license with valid and invalid values

Tests for editing version details - part one

---

pages/desktop/frontend/details.py

Simplifies and makes the method for getting the addon detail name more robust.

Update the method for detail addon name

---

tests/api/test_addon_uploads.py

- tests for editing a version custom license (valid and invalid cases)
- tests for editing a version compatibility (valid and invalid cases)

Add more tests for editing version license and compatibility

---

pages/desktop/frontend/home.py
scripts/custom_waits.py
tests/frontend/test_users.py

I've updated our custom wait methods to use a method definition instead of class to match the selenium `expected_conditions` model.

Update custom waits from class to methods

---

api/api_helpers.py
tests/api/test_api_versions_edit.py

Add tests for uploading and changing version source code and a method that allows comparisons between source files attached to the versions.

Add tests for source code upload

---

tests/api/test_api_authors_edit.py

- a test for listing addon authors pending for confirmation
- a test for fetching the details for addon authors pending for confirmation
- a test for updating pending author details (role, visibility on the site)
- tests for deleting a pending author and confirming a deleted invitation

Add more tests for pending addon authors

---

tests/api/test_api_authors_edit.py

- tests for adding multiple pending authors
- test for confirming author invites
- adding/editing/deleting authors with authors having a developer role (not allowed)
- test deleing pending and active authors

add more tests for additional authors and role permissions

---

tests/api/test_api_authors_edit.py

This PR includes the final tests for the API addon authors:
- tests that verify the actions available and not available to authors with developer roles
- editing the details for an exiting author with the addon owner

Add final tests for API addon authors

---

tests/frontend/test_sanity.py

This test needs more investigation so I'm skipping until I get more time to get to it.

skip about:addons search test

---

pages/desktop/frontend/details.py
regions/desktop/categories.py
tests/frontend/test_addon_detail.py
tests/frontend/test_extensions.py
tests/frontend/test_themes.py
tests/frontend/test_translations.py

- small coverage improvements to addon details, extensions and themes pages
- small refactoring to some of the methods supporting these tests

Small refactoring and test coverage improvements

---

pages/desktop/base.py
pages/desktop/frontend/search.py
tests/conftest.py
tests/frontend/test_collections.py
tests/frontend/test_extensions.py
tests/frontend/test_home.py
tests/frontend/test_ratings.py
tests/frontend/test_sanity.py
tests/frontend/test_search.py
tests/frontend/test_themes.py
tests/frontend/test_users.py
tests/frontend/test_versions.py

- refactoring some search methods and tests
- improvements to some of our homepage tests

More refactoring and test improvements

---

prod.json

Change a variable in the prod collection tests.

Update variable for privacy prod collection

---

tests/api/test_addon_uploads.py
tests/api/test_api_versions_edit.py

There were some updates to the expected status codes in the addons submissions API, so I've updated them in our tests as well.

Update status codes for some api tests

---

tests/api/test_api_versions_edit.py

An option to disable and re-enable an addon version as a developer has been added to the submissions API. I've added a test to cover this functionality.

Add test for API enable/disable versions

---

pages/desktop/frontend/users.py
tests/frontend/test_users.py

Simplify the user notifications test to (hopefully) make it more stable.

update the user notification tests to be more stable

---

tests/api/test_addon_uploads.py

Also remove redundant `print` and add message to the `assert` statement instead. 
Will merge once the code reaches stage.

Add new reserved guid to the addon submission test

---

dev.json
pages/desktop/developers/submit_addon.py
stage.json
tests/devhub/test_devhub_home.py

Add tests covering the developer agreement devhub page.

Devhub distribution agreement

---

tests/devhub/test_addon_submissions.py
tests/frontend/test_users.py

These changes will land on Tuesday EOD on stage so the tests will not fail (probably) once the ne tag is pushed.

change things around compat selection
