test_home.py
The Contact page we link to in the footer no longer exists - a 404 is triggered. Until the new resource is added, I've changed the link in the test to avoid build failures.
=> Temporary fix for the Contact page error linked in the footer

test_extensions.py
Adding tests for the three shelves present on the Extensions homepage. The scope is to validate that shelf items are displayed correctly and that each shelf opens up to a set of search results corresponding to the shelf sort criteria.
=> Adding tests for the Extensions homepage shelves

pages/desktop/home.py, regions/desktop/shelves.py, test_extensions.py, test_home.py
Fix #103 
While doing this I've realized that we have the `browse_all` function in two places: `pages/home.py` and `regions/shelves.py`.
I think the function should only exist in  `regions/shelves.py` because it's a shelf specific function.
I'll file a follow up issue to track the changes that need to be done to make this move.
=> Make browse_all a function

test_themes.py
Similar to the tests added for Extensions landingpage shelves, I'm covering here the shelves present on Themes landingpage.
=> Add tests for Themes landingpage shelves

test_search.py
`test_uppercase_has_same_suggestions` sometimes fails because of this issue - https://github.com/mozilla/addons-server/issues/16610
=> xfail a search test due to some data issues on stage

pages/desktop/details.py, stage.json, test_addon_detail.py
With this PR I'm adding a new test module - `test_addon_detail.py` - which will contain tests specific for extensions and theme detail pages.
First, I'm adding some tests for add-on incompatibility messages.
=> Add tests for incompatible addons

tests/test_home.py
The link for the Firefox YouTube channel has been changed, so we needed to update our `test_social_footer_links` test.
=> Update YouTube link in footer test

pages/desktop/details.py, tests/test_addon_detail.py
I'm adding another test, this time covering the Permissions card from add-on detail pages:
=> Add test for addon Permissions card

tests/test_extensions.py, tests/test_themes.py
There has been a change in the Themes and Extensions Category landing pages URLs, so I had to remove an assertion since it is no longer valid in the new context.
=> Fix theme and extension category tests

tests/test_home.py
The youtube link has changed a couple times in the past, so I'm renaming it to just  'youtube.com' to keep the data valid if any other changes occur.
=> Fix youtube footer link

.circleci/config.yml, setup.cfg, tests/test_addon_detail.py
Trying to fix log output in html reports by updating the report title in circleci config and setup config files. 
Tweaked the cli arguments from setup.cfg and now we're capturing log output in pytest-html reports:
https://388-242947140-gh.circle-artifacts.com/0/ui-test-release.html
=> Fix log output in html report

tests/test_users.py
FxA bug that cased the test failures - https://github.com/mozilla/fxa/issues/8658
=> Skip login/logout tests because of an FxA bug

pages/desktop/details.py, pages/desktop/users.py, tests/test_addon_detail.py
A test that clicks on the add-on author link in the detail meta-card and verifies that the author profile page is opened.
=> Add-on author link in detail page

tests/test_search.py
The compatibility tests are more extensively covered in the addon detail suite, so this test is redundant here.
=> Deleting a test that is no longer relevant

custom_waits.py, pages/desktop/home.py, tests/test_home.py
The Secondary hero has three modules, each with a CTA link that points to various resources.  This test checks that those resources are available.
=> Tests covering linked content in secondary hero modules

pages/desktop/reviews.py
I've added waits to some of the elements which were causing intermittent test failures in the flag review menu.
=> Fix intermittent test failures for reviews flagging

setup.cfg
This will make the pytest-html report easier to interpret.
=> Minimize the amount of logs captured in the pytest html report

pages/desktop/static_pages.py, pages/desktop/users.py, stage.json, tests/test_users.py
The View Profile page identifies developer and theme artist user roles with some badges. I've added these tests to make sure that badges are correctly applied.
=> Add tests for user role badges

tests/test_users.py
Additionally, I've marked the login and logout tests as serial. I had a hunch that the logout tests might cause some race condition with other tests that require login when run in parallel.
=> Small change to the edit profile picture test

tests/test_users.py
Adding some more user tests that require login to the serial suite to see if this helps FxA to better handle the load of multiple login requests that occur in the parallel suite.
=> Mark more user tests as serial

.circleci/config.yml, tests/test_collections.py, tests/test_ratings.py, tests/test_users.py
In the past weeks, I've noticed some instability in the serial tests, with failures caused mostly by FxA being unresponsive (server errors, timeouts etc).
First, I've tried to mitigate that by adding more test users (see https://github.com/mozilla/addons-release-tests/pull/339), but it didn't work
Now, I'm trying to run the serial tests - which are requiring logins in most cases - in separate jobs based on the functionality tested. I'm hoping that by running separate jobs, which in turn are run in separate containers on CI, we're going to see some stability improvements, or, at least, isolate failing jobs more effectively. 
I've also upgraded the windows orb we were using, to the new 2.4.1 version.
=> Upgrade windows orb and split serial jobs

.circleci/config.yml, requirements.txt
I managed to make `pytest-rerunfailures` to run locally if I removed the `pytest-depends` dependency (which we are not using).
Let's see if it will work on CI as well.
=> Try again to add pytest-rerunfailures

.circleci/config.yml, pages/desktop/devhub.py, tests/test_devhub.py
Started adding test for the Developer Hub homepage with the main footer, which is a tedious process to be tested manually every week.
Devhub tests will run in a separate job, so I've added it to the config.
=> Tests for the devhub homepage main footer

.github/dependabot.yml
Based on https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit - this should only trigger one PR from dependabot per day.
=> limit dependabot PRs to one per day to avoid concurrent runs

pages/desktop/base.py, pages/desktop/details.py, pages/desktop/home.py, requirements.txt
Now that `pypom` has been upgraded to be compatible with selenium 4, I was able to run the tests with the new selenium version and noticed that the `switch_to_window` option is no longer supported. I've updated the methods that rely on that function to be compatible with selenium 4.
=> Modify windowhandles methods to work with selenium 4

pages/desktop/base.py, pages/desktop/login.py, tests/test_users.py
I've added two methods to handle new account registration:
- a method that accesses the `restmail` endpoint to get the fxa verification code
- a method that handles the FxA registration form input
=> Add fxa register methods and test

setup.cfg, tests/test_collections.py
- skip a collection test until an issue with the collection form on AMO is fixed
- reduce amount of logs captured
=> Skip a test due to an AMO bug and limit traceback logs

pages/desktop/base.py
AMO doesn't use "locale" as  a query  parameter, so passing it to the `base_url` doesn't change anything with the site language.
=> Remove locale query param from base_url

.circleci/config.yml, pages/desktop/developers/addons_manage.py, pages/desktop/developers/devhub_home.py, tests/test_devhub_home.py
Added three simple tests for the logged page view :
- clicking My Addons link in the Developer Hub homepage header
- verifying the elements in the developer homepage main  banner
- clicking on the user avatar nd checking that the user is sent to the frontend profile page
I've also refactored the `DevHub` page objects class into `DevHubHome` to make it more clear that these are elements present in the the homepage only, since DevHub by itself is too generic given the size of the developer pages as a whole. 
I've also renamed the `test_devhub.py` file to `test_devhub_home.py`
=> Rename devhub page and tests to devhub home and add a few more tests for logged in homepage view

.circleci/config.yml
CircleCi will  deprecate scheduling workflows directly within [.circleci/config.yml](https://github.com/mozilla/addons-release-tests/compare/migrate-circleci-scheduled-jobs?expand=1#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47).
They have added a different method for scheduling pipelines, as explained in https://circleci.com/docs/2.0/scheduled-pipelines/#get-started
I've set up the `scheduled_stage_release_run` trigger in the CircleCI Project settings and, hopefully, our scheduled release run will continue to run fine on Wednesdays at the established hour.
=> Migrate CircleCI scheduled runs to the new scheduling model

.circleci/config.yml, pages/desktop/frontend/language_tools.py, prod.json, stage.json, tests/conftest.py, tests/frontend/test_collections.py, tests/frontend/test_sanity.py
Included in this PR:
- CircleCi configs for prod tests
- updated firefox capabilities to use e clean profile when running prod install tests
- added page objects for the Language Tools page
- added install tests to be run on production with data available there
Note that the sanity tests added so far were mostly used as a trial run for the CircleCI set-up (new jobs for sanity runs, scheduling jobs, holding jobs for approval)
Once I'm happy with the system, I'm going to select other strategic tests, from the ones we already have, to be included in the sanity runs - they will be marked with `pytest.mark.sanity`.
=> Initial setup for sanity tests run

pages/desktop/frontend/collections.py, tests/frontend/test_collections.py
Skipping the collection notes test until a bug in AMO is fixed.
Also, this test was added twice in the collections tests script (by accident most likely), so I've deleted one of the occurrences.
=> Fix collection notes test

tests/frontend/test_home.py
A small change that removes the check for the footer site status in `test_addons_footer_links`. This link  has been removed from AMO frontend - https://github.com/mozilla/addons-frontend/issues/11308
=> Remove check for site status footer link

pages/desktop/frontend/search.py, tests/frontend/test_search.py
The purpose of these tests is to verify that combining filters when searching for add-ons works as expected.
Also, these tests verify that filters remain applied when searching for a new term.
=> Add tests for search filters combinations

pages/desktop/frontend/blog.py, tests/frontend/test_blog.py
Add three tests for the blog page to be run during sanity testing (stage is not covered yet because the blog doesn't have a dedicated infrastructure that supports installations):
- add-on installation from the blog
- checking that add-on links go to AMO addon details page
- checking that author links go to AMO user profile page
=> Add tests for install and links in the blog addon cards

pages/desktop/about_addons.py, pages/desktop/frontend/details.py, pages/desktop/frontend/search.py, tests/conftest.py, tests/frontend/test_sanity.py
Included in this PR:
- page objects for the recommendations pane in about:addons
- tests covering the recommendations pane in about:addons 
- some tweaking to firefox capabilities to make sure about:addons is populated with data 
These tests will be run during the sanity run.
=> Add sanity tests for about:addons page

pages/desktop/frontend/blog.py
In test_addon_cards_loaded_correctly(), the case where add-on is not rated yet was not accounted for. 
This has been fixed in the current commit.
=> fix bug in test_addon_cards_loaded_correctly() from test_blog.py

pages/desktop/base.py, pages/desktop/developers/devhub_home.py, pages/desktop/developers/submit_addon.py, stage.json, tests/devhub/test_devhub_home.py
Added tests for devhub home page:
-test that verifies my add-ons paragraph (only displayed when user has no submitted add-ons)
-tests that verifies 'Submit Your First Add-on' and 'Submit Your First Theme' buttons (displayed the same as above)
-test for license message from page footer
=> Coverage test devhub home

pages/desktop/base.py
Adds an extra pause in the action chains which, hopefully, will fix de intermittent failures in the `test_user_menu_devhub_links` test.
=> add an extra pause in action chains

pages/desktop/base.py, tests/devhub/test_devhub_home.py, tests/frontend/test_home.py
Add some improvements to the homepage footer tests:
- add additional page checks
- add wait messages 
- add missing test for the copyright message and links
- update copyright message and links test in the devhub suite
=> Improve footer tests

tests/conftest.py, tests/frontend/test_install.py
We already had these tests in the sanity suite; I'm adding them in the stage release run too to make sure we test about:addons installs regularly.
=> Add about:addons install tests to stage runs too

pages/desktop/frontend/details.py, tests/frontend/test_addon_detail.py, tests/frontend/test_collections.py
I'm trying to reduce the amount of logins we do for the sanity tests, so I'm moving most of the collection tests to sessionauth.
=> Move collection creation tests to sessionauth

tests/api/test_addon_uploads.py
- a test for missing the mandatory name field in `manifest.json`
- a test for missing a `description` field in `manifest.json` or a `summary` in the JSON payload
- a test for invalid `version` numbers set in `manifest.json`
=> Add tests for some invalid manifest instances

tests/devhub/test_devhub_home.py
Reality is no longer a supported product, so he link was removed from the Footer.
=> Remove Reality link from Devhub footer test

dev.json, tests/api/test_addon_uploads.py
- a test for editing addon names with a trademark name (Mozilla/Firefox)
- test for invalid addon homepage values
- test for addon invalid email domains
- test for invalid `experimental` and `requires payment` fields
- test for valid/invalid contribution domains
- test for invalid addon tags 
Edit: failing test is unrelated; caused by a basket email service disruption
=> Tests for editing addons with invalid payloads - part two

pages/desktop/frontend/login.py
The previous locator used in this wait is no longer present.
=> Update locator in login method

.circleci/config.yml
Upgrade windows executor size from medium to large, as a first step to debug CircleCI hanging jobs.
=> Increase win executor size

pages/desktop/frontend/details.py, tests/frontend/test_addon_detail.py
- a test covering all the builtin extension licenses provided by AMO
- a test for extensions released under 'All Rights Reserved' which should be a simple text name not linked to any external or internal page
=> Add tests for all the builtin extension licenses

pages/desktop/frontend/details.py, tests/frontend/test_addon_detail.py
External links added in addon fields such as homepage, support site, summary, description, developer comments, privacy policy/eula, version release notes, custom license text need to be redirected through the https://stage.outgoing.nonprod.webservices.mozgcp.net domain. Also, when a user clicks on these links, the external page added by the addon developer should open correctly.
=> Add tests for outgoing URLs in addon fields

dev.json, tests/api/test_addon_uploads.py
- invalid scenarios for deleting an addon through the API - for example, using an invalid delete token, deleting an addon with a user that is not the addon author
- reusing GUIDs to upload a new addon
=> Add tests for deleting addons through the API

.circleci/config.yml, dev.json, tests/api/test_addon_uploads.py, tests/api/test_api_addons_edit.py, tests/api/test_api_versions_edit.py
The API tests were all added in the same file until now, but that was becoming quite large. I've chosen to split the tests into multiple categories to make them easier to track. We now have:
- a test file that includes only upload tests
- a test file for editing addon details
- a test file for editing version details
Will follow:
- a test file for editing addon authors 
There were no changes done to the actual tests, except for some formatting and small corrections. 
I've also added some short documentation for each test file to make it clear what test includes and what API endpoints it uses.
=> Split API tests into different files

tests/api/test_addon_uploads.py
- a test for uploading addons with a reserved guid using an authorized account
- a test for uploading addons with a trademark name using an authorized account
- amended a test from previous PR  (https://github.com/mozilla/addons-release-tests/pull/662) to test privileged addon uploads with authorized accounts; in the previous PR I was testing with an unauthorized account twice.
=> Add more tests for uploads with special permission requirements

tests/api/test_addon_uploads.py
Sometimes, language pack submissions were failing with a "Upload not valid" error, which shouldn't be the case. This message can sometimes trigger when the upload hasn't been fully processed yet, so I'm increasing the wait time to see if this solves the issue. 
This PR is added on top of https://github.com/mozilla/addons-release-tests/pull/664 because I've only changed a wait time.
=> Give extra time for langpacks to be processed before submission

pages/desktop/about_addons.py, tests/frontend/test_install.py
The previous install tests were parameterized to run with each add-on type, but that had some limitations in the more varied verifications we could do depending on the addon type installed.
I've chosen to split the tests and include more verifications, such as making sure that the addons are listed/delisted in their respective tabs in about:addons after installation/uninstallation. 
I've also added a new test that checks the Enable/Disable function in AMO and about:addons.
=> Refactor install tests

tests/devhub/test_devhub_home.py
The site status link has been removed from the devhub, so we should also remove it from our tests.
=> Remove site status from devhub footer links test

tests/frontend/test_sanity.py
Just a small update to the about addons theme install test to cover situation when we have a name mismatch, i.e. verify that the theme installed correctly base on other values, such as the theme image source.
=> Update about addons install theme test

pages/desktop/frontend/search.py, pages/desktop/frontend/users.py, tests/frontend/test_users.py
I've added a new test in the user profiles suite covering the addon cards (extensions and themes) for users that are both developers and theme artists.
=> Add test for user profile addon cards

tests/api/test_addon_uploads.py
Small fix to update a validation message for invalid version strings.
=> Update validation message for invalid version strings

.circleci/config.yml, dev.json, scripts/reusables.py, tests/frontend/test_addon_detail.py, tests/frontend/test_search.py, tests/frontend/test_versions.py, translations.json
We used to run our test only on AMO stage where the test data is more reliable. After a discussion with the dev team, we decided to add some regression suites to run on AMO -dev as well. The tests will run once a day (over night).
- adding variables to `dev.json` with test data from AMO dev
- creating the CircleCI config and scheduling to run frontend parallel tests on AMO -dev - see https://app.circleci.com/pipelines/github/mozilla/addons-release-tests/1756/workflows/04486e7c-ab2e-4612-94ce-23d6fa5a9e59/jobs/6548
- small refactoring to some tests to make them compatible between dev and stage
The test failure is unrelated and was fixed in https://github.com/mozilla/addons-release-tests/pull/682
=> Add variables and config to run parallel tests on AMO dev

dev.json, tests/api/test_api_authors_edit.py
- tests for verifying addon active author details
- test for verifying that addons require at least one listed author and owner
- tests for unauthorized authors trying to edit addon author details
=> Add more tests that cover addon authors

requirements.txt
Since the upgrade to `pytes-html = 3.2.0` there have been some intermittent encoding errors raised from `charmap` (the encoding /decoding utility included with Windows operating systems). We should wait for a future release before we upgrade again.
=> downgrade pytest-html due to encoding error

.circleci/config.yml, dev.json, stage.json, tests/devhub/test_devhub_home.py
- circleci config
- variables for AMO -dev
- small test updates to make the compatible
=> Add devhub homepage tests to dev regression

.circleci/config.yml, dev.json
This PR adds the config and variables necessary for running the addon devhub submission tests on AMO -dev.
=> Amo dev submission tests

pages/desktop/frontend/collections.py, tests/frontend/test_collections.py
The collection description has been limited to 280 characters. I've added an option to clear the previous description in a collection before adding new text in order to not reach the character limit.
=> Update collection description edits

pages/desktop/frontend/static_pages.py, tests/frontend/test_static_pages.py
Some small updates to static pages tests and removing some redundancies. 
Note that the failing API tests were caused by some timeout issues on AMO -dev which are currently being investigated by Ops.
=> Small updates to static pages tests

tests/devhub/test_addon_submissions.py
There have been some changes to autoapproval on prod which makes this autoapproval test not applicable. Until I have a new solution, I'm removing the test from the sanity suite.
=> Remove autoapproval test from sanity suite

.circleci/config.yml, stage.json, tests/api/test_addon_uploads.py, tests/api/test_api_versions_edit.py
Previously, the API submission tests were running on -dev but I'm moving them to stage with a plan to also include them in the -dev regression runs at a later date when -dev becomes more stable (we had some timeout issues there for the pat few weeks). 
I've also increased the wait time between requests slightly because I've notice some addon creation tests failing sometimes because the addon upload request was not fully processed (the API returns 201 early, before the necessary upload validations finish running in the background).
=> Move API tests to run on stage instead of dev

api/api_helpers.py, dev.json, pages/desktop/developers/manage_versions.py, prod.json, stage.json, tests/devhub/test_addon_submissions.py
- create a method that allows to retrieve the version string for an addon's latest version
- create a test that verifies that new unlisted version submissions for an already approved addon are being auto-approved
Note: the failed job is not related to my changes; the failures are caused by AMO -dev being really unstable for the past few weeks so running tests on -dev is a bit unreliable right now; that being said, this shouldn't block this PR because the changes made were tested and the related jobs are passing
=> Add test for new version autoapproval

pages/desktop/developers/manage_versions.py, tests/frontend/test_home.py
- give auto-approval a bit over 5 minutes to run before exiting the wait loop
- remove recommended themes shelf test from sanity since is no longer part of the homepage (for the moment)
=> Increase autoapproval wait and remove test from sanity

pages/desktop/frontend/details.py, tests/frontend/test_ratings.py
A new feature was added recently that will deny user review submissions if one or more words in the review body are matching a  flagged word.
This test verifies this feature.
=> Add test for banned words in user reviews

.circleci/config.yml, dev.json, pages/desktop/developers/submit_addon.py, stage.json, tests/devhub/test_addon_submissions.py, tests/devhub/test_devhub_home.py
- restructuring of the developer hub tests (moved all tests that are part of the submission flow into the `test_addon_submissions` module)
- some corrections in the circleci config file
- page objects and test for the addon distribution page
=> Add test for addon distribution page

dev.json, pages/desktop/developers/submit_addon.py, stage.json, tests/devhub/test_addon_submissions.py, tests/devhub/test_devhub_home.py
- page objects for the devhub upload page (where users validate their file uploads)
- tests for the addon upload and validation age
=> Add tests for the devhub upload file page

dev.json, pages/desktop/developers/manage_versions.py, stage.json, tests/devhub/test_addon_edit.py
This PR contains:
- page objects for the Listing visibility section in devhub manage version page
- test for setting an addon invisible/visibile
=> Set an addon invisible through devhub

dev.json, pages/desktop/developers/manage_versions.py, stage.json, tests/devhub/test_addon_edit.py
- page objects for the version list Delete/Disable modal
- a test for disabling and re-enabling a version from devhub
=> Add test for disabling a version through devhub
